# Generated by Django 2.0.5 on 2018-07-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre', max_length=200)),
                ('apellido', models.CharField(help_text='Apellido', max_length=200)),
                ('curso', models.CharField(help_text='Curso', max_length=200)),
            ],
        ),
    ]
